============================= test session starts ==============================
rootdir: $(SOURCE_DIR), inifile: pytest.ini
collected 17 items / 2 errors

tempora/__init__.py ..........
tempora/timing.py ...
tempora/utc.py .
tests/test_timing.py ..

==================================== ERRORS ====================================
_______________ ERROR collecting tempora/tests/test_schedule.py ________________
tempora/tests/test_schedule.py:7: in <module>
    import freezegun
E   ImportError: No module named 'freezegun'
_______________ ERROR collecting tempora/tests/test_schedule.py ________________
tempora/tests/test_schedule.py:7: in <module>
    import freezegun
E   ImportError: No module named 'freezegun'
====================== 16 passed, 2 error in  x seconds ======================
